#basePath=C:\\mnt\\
#logPath=C:\\mnt\\log_SmartNova\\
basePath=/mnt/smartnova/
logPath=/mnt/smartnova/log/
apikey=4b7848351259b7a9ee1fbc1bcdac7c4a
secretKey=4eec6b411d36069723b5310e1b5484fe
username=developers@smartoop.it
host=smtp.gmail.com
port=587
VALIDATION_STRING=VALIDATION
ALGORITHM=AES
ENCODED_KEYS=Yw6iVziVob3na+d5FVAaQg,Yp6iVziVow3nu+d5SVTaQb,Yg2iIziSub2np+d3FVVaQl